repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check --fix .
        language: system
        pass_filenames: false
      - id: ruff-format-check
        name: ruff format check
        entry: uv run ruff format --check .
        language: system
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: uv run mypy src/
        language: system
        pass_filenames: false
      - id: prettier
        name: prettier
        entry: npx prettier --check "**/*.{md,yaml,yml,json}" ".prettierrc"
        language: system
        pass_filenames: false
      - id: markdownlint-cli2
        name: markdownlint-cli2
        entry: npx markdownlint-cli2 "**/*.md"
        language: system
        pass_filenames: false
