profile = "dev"

[paths.dev]
db = "./data-dev.db"
logs = "./logs-dev"

[logging.dev]
retention_days = 7
level = "DEBUG"

[logging.production]
retention_days = 14
level = "INFO"

[paths.production]
db = "~/.local/share/sm-tracker/data.db"
logs = "~/.local/share/sm-tracker/logs"
